[package]
name = "backend"
version = "0.1.2"
edition.workspace = true
authors.workspace = true
description = "Email auth provider"

[lib]
crate-type = ["cdylib"]

[features]
default = ["username"]
username = []


[dependencies]
serde.workspace = true
serde_json.workspace = true
http.workspace = true
bytes.workspace = true
diesel.workspace = true
argon2.workspace = true
chrono.workspace = true
validator.workspace = true
ft-sdk.workspace = true
common.workspace = true
smallvec.workspace = true
