[package]
name = "lets-auth"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
ft-sdk.workspace = true
serde_json.workspace = true
http.workspace = true
serde.workspace = true
