name: Upload lets-auth to FifthTry

on:
  push:
    branches: [ main ]
    paths:
      - lets-auth.fifthtry.site/**
      - email-auth-provider/**
      - mobile-auth-provider/**
      - scripts/*.sh
      - .github/workflows/app-to-ft.yml
      - Cargo.toml


jobs:
  upload-to-fifthtry:
    runs-on: ubuntu-latest
    env:
      FIFTHTRY_SITE_WRITE_TOKEN: ${{ secrets.FT_LETS_AUTH }}
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
      - run: ./scripts/publish-app.sh
